### ISSUE TITLE
ERROR running ./run.sh file

### ISSUE THREAD

**Issue by adityasriv22** [jpaffrath/docker-openplc#1]
Getting this error while running the run.sh file from inside the container

Error: UNIQUE constraint failed: Slave_dev.dev_name
/home/openplc/OpenPLC_v3/start_openplc.sh: line 2: cd: webserver: No such file or directory
python2: can't open file 'webserver.py': [Errno 2] No such file or directory

**Comment by jpaffrath** [comment]
Please try again with my [latest fix](https://github.com/jpaffrath/docker-openplc/commit/9e92ff2cc6d7b46a2313c2fd24a1233118d4f638).
I can't reproduce your error but a Python Module was missing.
With the fix my container just runs fine.

**Comment by adityasriv22** [comment]
Thanks!

**Comment by jpaffrath** [comment]
You are welcome!
Does the fix resolve your error?

**Comment by adityasriv22** [comment]
Yes, but i changed the scriptz directory traversal as it was not changing
directory.
